type MonacoApi = typeof import("monaco-editor");

const KEYWORDS_BY_LANGUAGE: Record<string, string[]> = {
  c: [
    "auto",
    "break",
    "case",
    "char",
    "const",
    "continue",
    "default",
    "do",
    "double",
    "else",
    "enum",
    "extern",
    "float",
    "for",
    "goto",
    "if",
    "int",
    "long",
    "return",
    "short",
    "signed",
    "sizeof",
    "static",
    "struct",
    "switch",
    "typedef",
    "union",
    "unsigned",
    "void",
    "volatile",
    "while",
    "include",
    "define",
    "printf",
    "scanf",
    "malloc",
    "free",
    "NULL",
  ],
  cpp: ["class", "namespace", "template", "virtual", "public", "private", "protected", "new", "delete"],
  csharp: [
    "class",
    "namespace",
    "using",
    "public",
    "private",
    "protected",
    "static",
    "void",
    "int",
    "string",
    "bool",
    "var",
    "if",
    "else",
    "for",
    "foreach",
    "while",
    "return",
    "new",
    "true",
    "false",
    "null",
    "async",
    "await",
    "Console",
    "WriteLine",
  ],
  javascript: [
    "const",
    "let",
    "var",
    "function",
    "return",
    "if",
    "else",
    "for",
    "while",
    "class",
    "import",
    "export",
    "from",
    "async",
    "await",
    "true",
    "false",
    "null",
    "undefined",
    "console",
    "log",
  ],
  typescript: [
    "const",
    "let",
    "interface",
    "type",
    "function",
    "return",
    "if",
    "else",
    "for",
    "while",
    "class",
    "import",
    "export",
    "from",
    "async",
    "await",
    "true",
    "false",
    "null",
    "undefined",
    "string",
    "number",
    "boolean",
  ],
  python: [
    "def",
    "class",
    "if",
    "elif",
    "else",
    "for",
    "while",
    "return",
    "import",
    "from",
    "True",
    "False",
    "None",
    "print",
    "pass",
    "break",
    "continue",
  ],
  java: [
    "class",
    "public",
    "private",
    "static",
    "void",
    "int",
    "String",
    "if",
    "else",
    "for",
    "while",
    "return",
    "new",
    "true",
    "false",
    "null",
    "System",
    "out",
    "println",
  ],
  html: ["div", "span", "p", "a", "img", "ul", "li", "h1", "h2", "button", "input", "form", "script", "style"],
  css: ["color", "background", "margin", "padding", "display", "flex", "grid", "width", "height", "font-size"],
  sql: ["SELECT", "FROM", "WHERE", "INSERT", "INTO", "UPDATE", "DELETE", "JOIN", "ORDER", "BY", "GROUP", "HAVING"],
  json: ["true", "false", "null"],
  markdown: ["#", "##", "###", "**", "*", "```", "-", "[]", "()"],
};

const registered = new Set<string>();

export function registerKeywordCompletions(monaco: MonacoApi): void {
  for (const [languageId, keywords] of Object.entries(KEYWORDS_BY_LANGUAGE)) {
    if (registered.has(languageId)) {
      continue;
    }
    registered.add(languageId);

    monaco.languages.registerCompletionItemProvider(languageId, {
      triggerCharacters: [".", " ", "(", "<"],
      provideCompletionItems(model, position) {
        const word = model.getWordUntilPosition(position);
        const range = {
          startLineNumber: position.lineNumber,
          endLineNumber: position.lineNumber,
          startColumn: word.startColumn,
          endColumn: word.endColumn,
        };

        const query = word.word.toLowerCase();
        const filtered = query
          ? keywords.filter((kw) => kw.toLowerCase().startsWith(query))
          : keywords;

        return {
          suggestions: filtered.slice(0, 40).map((label) => ({
            label,
            kind: monaco.languages.CompletionItemKind.Keyword,
            insertText: label,
            range,
          })),
        };
      },
    });
  }
}
